steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-frontend:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-frontend:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://fraud-forge-backend-REPLACE.run.app'
      - '-f'
      - 'frontend/Dockerfile'
      - 'frontend/'

  # Push the Docker image to Artifact Registry (not GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-frontend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fraud-forge-frontend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-frontend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-frontend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-frontend:latest'

timeout: '1200s'

