steps:
  # Build the Docker image (AMD64 for GCP Cloud Run compatibility)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-backend:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-backend:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend/'

  # Push the Docker image to Artifact Registry (not GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-backend'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'fraud-forge-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '0'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-backend:$SHORT_SHA'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/fraud-forge-images/fraud-forge-backend:latest'

timeout: '1200s'

